# Generated by Django 2.1.7 on 2019-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190216_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvbanners',
            name='acls_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rvbanners',
            name='alt_contenttype',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rvaccountpreferenceassoc',
            unique_together={('account_id', 'preference_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvaccountuserassoc',
            unique_together={('account_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvaccountuserpermissionassoc',
            unique_together={('account_id', 'user_id', 'permission_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvaclschannel',
            unique_together={('channelid', 'executionorder')},
        ),
        migrations.AlterUniqueTogether(
            name='rvdatabkta',
            unique_together={('server_conv_id', 'server_ip')},
        ),
        migrations.AlterUniqueTogether(
            name='rvdatabktavar',
            unique_together={('server_conv_id', 'server_ip', 'tracker_variable_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvdatabktc',
            unique_together={('interval_start', 'creative_id', 'zone_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvdatabktm',
            unique_together={('interval_start', 'creative_id', 'zone_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvdatabktr',
            unique_together={('interval_start', 'creative_id', 'zone_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvdatabktvaste',
            unique_together={('interval_start', 'creative_id', 'zone_id', 'vast_event_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvdatarawtrackerimpression',
            unique_together={('server_raw_tracker_impression_id', 'server_raw_ip')},
        ),
        migrations.AlterUniqueTogether(
            name='rvdatarawtrackervariablevalue',
            unique_together={('server_raw_tracker_impression_id', 'server_raw_ip', 'tracker_variable_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvpasswordrecovery',
            unique_together={('user_type', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rvvariablepublisher',
            unique_together={('variable_id', 'publisher_id')},
        ),
    ]
